### ISSUE TITLE
add_dimension doesn't load default type

### ISSUE THREAD

**Issue by jonathom** [Open-EO/openeo-web-editor#129]
The function `add_dimension` doesn't load the parameter `type` (default is `other`) into the process graph. Even when clicking on `type` -> `other` it is not added. Only when selecting a different option (`spatial, temporal, bands`) the parameter is added to process graph. This leads to the error "Process n/a parameter 'type' is required" when one would expect the default value being set automatically.

When omitting the parameter for example in an R script, it is correctly added to the graph.

Example: Add `add_dimension` to a (empty) graph, give it name and label and look at the code tab.

**Comment by m-mohr** [comment]
Yes, default values are not added to the process graph. That is expected behavior. If the back-end reports a parameter as optional (and only then it's not added to the parameters) but drops an error then, it seems that's a back-end issue. So I'd report that to the back-end.

**Comment by soxofaan** [comment]
> it seems that's a back-end issue

confirmed, this is issue in VITO backend. I will address this in Open-EO/openeo-python-driver#59

> Yes, default values are not added to the process graph. That is expected behavior.

I disagree here, if a user actively selects a value that happens to be the default value, I would still add it explicitly as argument (instead of depending that the backend will fill it in through a default value mechanism). 
In principle, backends could change default values in their process specs, so differences in default values would ruin reproducability of process graphs that are built with the web editor. If the web editor allows to set these arguments instead, users can work around that.
