### ISSUE TITLE
Flags for timeout after job creation request and disable automatic refresh of jobs tab

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-web-editor#148]
For our local instance of the Web Editor, it would be nice to have:
1. A variable to set the time that the editor waits for the response (after pressing the create batch job)
2. A variable/flag to disable jobs refresh (we would like to avoid unnecessary load at our back-end side)

**Comment by m-mohr** [comment]
> 1. A variable to set the time that the editor waits for the response (after pressing the create batch job)

That's actually part of the JS client, I just realized. I've just checked it and except for the capabilities (`GET /`) there is no timeout defined. So this seems to be more an issue of either your back-end or the browser, both I can't influence. But why is creating a job so slow (tens of seconds?) anyway? 

> 2. A variable/flag to disable jobs refresh (we would like to avoid unnecessary load at our back-end side)

Be aware that you won't get any updates then. So for example, if you submit a job, it will stick there as "queued" forever until you change tabs. Therefore I'd rather implement a config option for the reload time (so that you can reload all 10mins instead of 2 minute, for example). Same for the user details, web services, files etc.

**Comment by clausmichele** [comment]
> That's actually part of the JS client, I just realized. I've just checked it and except for the capabilities (`GET /`) there is no timeout defined. So this seems to be more an issue of either your back-end or the browser, both I can't influence. But why is creating a job so slow (tens of seconds?) anyway?

Thanks, then we need to solve it from our back-end side.

> Be aware that you won't get any updates then. So for example, if you submit a job, it will stick there as "queued" forever until you change tabs or request the job details (via the "i" button). Therefore I'd rather implement a config option for the reload time (so that you can reload all 10mins instead of 2 minute, for example). Same for the user details, web services, files etc.

Yes, instead of turning it completely off it would be enough being able to increase the time.

**Comment by m-mohr** [comment]
I've added support for it in v0.7.4 (available on the dev branch, not deployed to editor.openeo.org yet).
You can set it in config.js, the option is called `dataRefreshInterval`.
