### ISSUE TITLE
Context sensitive alert for missing data (with refresh button)

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-web-editor#231]
from https://github.com/openEOPlatform/architecture-docs/issues/179#issuecomment-1011249020 :
> The web editor refreshes jobs every two minutes. So for a retry to get all jobs you either need to wait for two minutes or login again.

Two minutes sometimes feels like ages  :stuck_out_tongue:  and having to re-login when you refresh the page is frustrating behavior.
Maybe add a button to refresh the job listing manually (optionally guarding users to press it too frequently)?

**Comment by m-mohr** [comment]
We had one in the past, but it didn't feel right as it doesn't really fit in as a workaround for a back-end issue you rarely need. Thus, we removed it. Also, this is only an issue right now because you can't switch between tabs as the Editor also reloads on every "tab" switch, but openEO Platform is simply too limited right now. Once File Upload or Secondary Web Services are implemented, the issue can be "worked around" without logging in again. So for simplicity, I'll not re-implement it.

**Comment by m-mohr** [comment]
Re-opening with a different idea for two issues that recently came up:
1. If discovery data is completely missing (recently came up several times on the VITO back-end), show a button to retry loading the data. We could show a warning instead of the list of processes/collections/...
    > [ The collections are missing due to a server issue | Retry ]
  
2. Show a refresh button, but only if federation:missing contains at least one item. Thise can be part of the planned "alert" that is shown when a back-end is missing in the results. So something like:
    > [ The list is incomplete as data from one back-end is missing: ABC | Reload | Close ]

So in contrast to the original proposal, this is context-sensitive and only shows these buttons/alerts when there's a real need for it.

**Comment by soxofaan** [comment]
> So in contrast to the original proposal, this is context-sensitive and only shows these buttons/alerts when there's a real need for it.

That would indeed cover the problem with partial/failing responses from back-ends.


But as a user the 2 minute poll interval sometimes feels frustratingly slow. Is it possible to make that interval context-sensitive/dynamic? E.g. If you just submitted a job, poll one or two times with 15s interval so you don't have to wait needlessly 2 minutes to see that your job failed for a stupid user error? Or when you detect that the webeditor is unused in a background tab, increase the poll interval to 5 (or longer) minutes?

**Comment by m-mohr** [comment]
But with the proposal above you could simply click refresh, so I don't really understand why the 2 mins are an issue any longer?

> to wait needlessly 2 minutes to see that your job failed for a stupid user error

Please note that jobs that are active (queued, running) are refreshed separately every ten seconds!

**Comment by soxofaan** [comment]
> But with the proposal above you could simply click refresh,  

I understood that that button only would appear when there was an error/partial result (I mean error in aggregating multiple backends, not a failing job). 

> Please note that jobs that are active (queued, running) are refreshed separately every ten seconds! So if you queue a job and it fails after 5 seconds, you'll be notified 10 secs after the queueing request. I think that's reasonably fast.

Ok I wasn't aware of these details, nevermind then

**Comment by m-mohr** [comment]
The refresh button is back :-)
