### ISSUE TITLE
Latest version and back-end compatibility (EURAC)

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-web-editor#232]
Hi Matthias,

the latest version 0.10.1 returns an error when trying to connect to EURAC:
![image](https://user-images.githubusercontent.com/31700619/149302242-c189bc72-fd8a-4405-838b-0ffa37a8b660.png)

Are there new constraints for being compatible? The 0.9.6 version works fine.

**Comment by jdries** [comment]
we discovered this one in the middle of a workshop! :-(

**Comment by soxofaan** [comment]
same issue here indeed with VITO backend  (https://editor.openeo.org/?server=https%3A%2F%2Fopeneo.vito.be)

because I'm logged in with EGI, instead of that error message toast, I get an error in the popup:

![Screenshot from 2022-01-13 10-46-40](https://user-images.githubusercontent.com/44946/149306944-d7518114-72a5-4683-979f-48d466d72145.png)

(in private browsing mode, so no existing cookies,  I get the error message toast as shown by @clausmichele )

**Comment by soxofaan** [comment]
I'm not sure, but the popup has an URL like https://aai.egi.eu/oidc/authorize?client_id=vito-default-client&redirect_uri=https%3A%2F%2Feditor.openeo.org&response_type=code&scope=openid%2Cemail%2Ceduperson_entitlement%2Ceduperson_scoped_affiliation%2Coffline_access&state=6ed...

the scope param is coma separated (%2C), while it should be space separted I htink (%20)

**Comment by soxofaan** [comment]
from some local experimenting it seems the comma separated scope string is indeed the problem

**Comment by soxofaan** [comment]
This is probably the commit that changed it from space-separated to comma-separated:
https://github.com/Open-EO/openeo-js-client/commit/6424d33183d93bc8654dd9a98a858edb3a1469ae#diff-a5e4b610c1dde3e4ca4c23c96048f9a52944c2209622044aac5606d2b969a291L227-R244

**Comment by m-mohr** [comment]
Sorry about that. Unfortunately, OIDC is not covered by tests due to its interactive nature. I'll issue a fix in the next 1-2 hours.

**Comment by m-mohr** [comment]
A fix has been issued and deplyoed. Sorry for any inconvenience caused.
