### ISSUE TITLE
UDP namespace with @ not allowed/supported?

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-web-editor#260]
I have a UDP in a namespace with an '@'.

The web editor can not properly load it because the @ and everything after it is dropped. Adding it again manually does trigger correct loading. Not sure if @ is an illegal character for namespace or some other problem?

https://editor.openeo.org/?server=https%3A%2F%2Fopeneo.vito.be&namespaces=u%3Adfa678cb9ab17f65d4f025e30fac5e0d90116176e44fd17d703419322747cbbd%40egi.eu&process=EVI%40u%3Adfa678cb9ab17f65d4f025e30fac5e0d90116176e44fd17d703419322747cbbd%40egi.eu

**Comment by m-mohr** [comment]
The implementation should follow the proposal in PR https://github.com/Open-EO/openeo-api/pull/348

In the proposal, @ plus username is meant to be used for user namespaces so it has a special meaning and is not allowed in user ids, I think.

Regexp for user id: `^[\w\-\.~]+$`
Regexp for namespaces: `^@?[\w\-\.~]+$`

Has been some time since I worked with user namespaces, but if you follow the PR and the regex, it should work.
