### ISSUE TITLE
Delay request for location

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-web-editor#264]
The editor currently asks access to current location on first view (before log in):
![Screenshot from 2022-06-08 12-19-14](https://user-images.githubusercontent.com/44946/173014032-4f26b476-db71-444a-9df8-54731b758112.png)

This feels a bit intrusive without obvious gain (location is only actually used when opening a map without obvious starting point)

Is it possible to delay the permission request to a later point, when the location is actually necessary?

**Comment by m-mohr** [comment]
I could delay it until after login, but it is annoying if I delay it until the map is actually shown, because:

1. Then the map loads twice, you have a refit in the location and that may disturb you when working with the map already (location is not always available immediately).
2. You get this request box everytime you open a new map, which is annoying (except you checked the box to remember the decision).

**Comment by soxofaan** [comment]
hmm, if that popup can not be delayed or only shown when necessary, then maybe this is a case where the cure (having to show the permission popup to everybody) is worse than the disease (not having an obvious map center for some edge cases)?

**Comment by m-mohr** [comment]
So for now it is only requested after the authentication screen and you can disable it for custom deployments via the `requestUserLocation` config option.

**Comment by m-mohr** [comment]
Different idea: Add a button to grab the location instead of using it by default.

**Comment by m-mohr** [comment]
Implemented, available on editor.openeo.org, soon also .cloud
