### ISSUE TITLE
Send token when clicking on 

### ISSUE THREAD

**Issue by danielFlemstrom** [Open-EO/openeo-web-editor#281]
When using the python client,  `results.get_asset('out_00000.tif').download()` sends the auth token to the openeo endpoint which allows us to keep different user's results apart. However, when clicking on the file link in the web-editor, the link is blindly followed which is a bit unfortunate. (at least for us since our users cannot (and should not) see each other's jobs or job results) 

![image](https://user-images.githubusercontent.com/12410550/194513426-55790aba-4fdf-4061-a5c1-a4696e3b59c1.png)

Which leads to a 
![image](https://user-images.githubusercontent.com/12410550/194513530-950f5510-bc3d-431d-98d3-a270847871b4.png)

Instead of blindly following the link, sending the auth header would make things much better.

**Comment by m-mohr** [comment]
This is as defined in the API documentation.
Batch job results intentionally use signed URLs instead of Auth headers so that they can be used e.g. in QGIS.
The signed URLs can only be retrieved with proper Auth headers so user's can't see each other results (if signed URLs are correctly implemented).
