### ISSUE TITLE
Support upload of geojson with multiple polygons

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-web-editor#299]
Question from internal user: can we provide multiple polygons as input to a process parameter by uploading a geojson file?

**Comment by m-mohr** [comment]
User can upload GeoJSON files (e.g. via drag&drop or copy/paste into the text editor) and these files can contain a FeatureCollection with multiple polygons. The Web Editor doesn't automatically combine the Polygons if you upload multiple files though.

Demo of drag&drop: 
![kml](https://user-images.githubusercontent.com/8262166/209120629-5f2e7d3c-d9ab-438a-9ec3-a9dda66e395c.gif)

**Comment by gutkinn** [comment]
No, not quite what I meant. When I upload a geoJSON with multiple polygons spread over a large area, openEO takes the entire extent of the area, rather than the polygons themselves. See example below, around 20 circular polygons of approx. 20m diameter, but generates an error because it's requesting a massive region rather than the individual polygons.
![image](https://user-images.githubusercontent.com/115157754/216603326-43d0bcef-6cda-4c78-8b8c-838cac5279cb.png)

**Comment by m-mohr** [comment]
Do you drag & drop this into the GeoJSON or Bounding Box view? You need to specifically select GeoJSON as shown above, otherwise, it will be converted into a bounding box.

If you've selected GeoJSON, you can see the process graph in the end and confirm that the GeoJSON is actually included and not a bounding box. And then it's a back-end issue and is on your table again @jdries  :-)

**Comment by gutkinn** [comment]
Looks like the CropSAR wizard doesn't have an option to select between geoJSON/bounding box:
![image](https://user-images.githubusercontent.com/115157754/216604631-79dcaa10-eb4f-4cc5-95ae-66b8fcf48216.png)

**Comment by m-mohr** [comment]
Then it selects GeoJSON by default as you see the corresponding map view. Can you confirm that you get a GeoJSON in the process graph?

**Comment by gutkinn** [comment]
The formatting is correct for geoJSONs I guess, and each feature is correctly delineated in the map view. They are MultiPolygons, not sure if that's a problem?
![image](https://user-images.githubusercontent.com/115157754/216606117-4c65ef30-99ac-4c8f-988f-4eaa0f2d912e.png)

**Comment by m-mohr** [comment]
Shouldn't be an issue. So then it's an issue on VITOs or SentinelHubs side. @jdries
